export interface ModuleFeature {
  title: string;
  description: string;
}

export interface ModuleData {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  heroTitle: string;
  heroSubtitle: string;
  heroImage: string;
  mainDescription: string;
  highlightStats: { label: string; value: string }[];
  featuresTitle: string;
  featuresDescription: string;
  features: ModuleFeature[];
  whoUsesSection: {
    title: string;
    description: string;
    userTypes: string[];
  };
  complianceNote: string;
  faqTitle: string;
  faqDescription: string;
  faqs: { question: string; answer: string }[];
}

export const modulesData: Record<string, ModuleData> = {
  "sales-management": {
    slug: "sales-management",
    title: "Sales Management",
    metaTitle: "Sales Management Software Saudi Arabia | AdoxERP Cloud ERP",
    metaDescription: "AdoxERP Sales Management helps businesses in Riyadh, Jeddah & Dammam manage quotations, orders, customer accounts & sales performance — ZATCA compliant & AI-powered.",
    keywords: [
      "sales management software Saudi Arabia",
      "sales ERP Riyadh",
      "quotation management KSA",
      "sales order software Jeddah",
      "CRM sales Dammam",
      "cloud sales software KSA"
    ],
    heroTitle: "Sales Management Software Built for Saudi Businesses",
    heroSubtitle: "Manage Your Entire Sales Cycle — From First Quote to Final ZATCA-Compliant Invoice",
    heroImage: "/img/sales-management-hero.png",
    mainDescription: "Every sale your business makes in Saudi Arabia — whether it is a single-branch retail transaction in Jeddah or a multi-order distribution deal in Riyadh — travels through a process. AdoxERP's Sales Management module brings that entire process into one intelligent platform. From the moment a lead becomes a prospect to the moment a ZATCA-compliant invoice is issued and payment is confirmed, your sales team has everything they need without switching systems, chasing spreadsheets, or waiting for end-of-month reports.",
    highlightStats: [
      { value: "360°", label: "Customer visibility" },
      { value: "Real-time", label: "Pipeline tracking" },
      { value: "ZATCA", label: "Compliant invoicing" },
      { value: "Arabic", label: "& English support" }
    ],
    featuresTitle: "What Sales Management Does in AdoxERP",
    featuresDescription: "AdoxERP Sales Management gives your team a single, connected workspace to manage every stage of the sales process. Quotations, sales orders, customer pricing, delivery tracking, and invoicing are all linked — so nothing falls through the cracks. The module connects directly to Inventory, Accounting, and CRM modules, meaning your sales team always knows what stock is available, what a customer owes, and what the finance team needs — without ever leaving their screen.",
    features: [
      {
        title: "Quotation & Proposal Management",
        description: "Create professional, branded sales quotations in Arabic and English in seconds. Set expiry dates, manage version history, and convert approved quotations directly into sales orders — no rekeying, no errors."
      },
      {
        title: "Sales Order Processing",
        description: "Manage sales orders from receipt to fulfilment with full traceability. Track order status, confirm delivery dates, and keep customers informed at every stage — whether they are in Riyadh, Jeddah, or anywhere across the GCC."
      },
      {
        title: "Customer Pricing & Discount Management",
        description: "Set tiered pricing, customer-specific discounts, and promotional pricing rules. AdoxERP enforces your pricing policy automatically, so every salesperson in every branch applies the right price every time."
      },
      {
        title: "ZATCA-Compliant Invoice Generation",
        description: "Every invoice generated by AdoxERP Sales Management is automatically ZATCA-compliant — formatted in the correct XML structure, stamped with a QR code, and submitted to the Fatoorah portal in real time. Zero manual intervention required."
      },
      {
        title: "Sales Performance Analytics",
        description: "Real-time dashboards show your top-performing salespeople, best-selling products, regional performance by city, and pipeline health — all in one view. Ask the AI chatbot for instant summaries in Arabic or English."
      },
      {
        title: "Multi-Branch Sales Visibility",
        description: "Whether your sales operation spans one office in Dammam or a network of branches across the Kingdom, AdoxERP gives management a unified view of every deal, every team, and every pipeline in real time."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP Sales Management in Saudi Arabia?",
      description: "AdoxERP Sales Management is used by sales-driven businesses of every size across Saudi Arabia. It is particularly valuable for wholesale and distribution companies in Riyadh managing high-volume order processing, retail chains in Jeddah needing consistent pricing across branches, manufacturing companies in Dammam and the Eastern Province that need to tie sales orders back to production, and service businesses billing clients on a project or milestone basis.",
      userTypes: [
        "B2B trading and distribution businesses in Riyadh with complex pricing and multi-branch operations",
        "Retail chains in Jeddah needing consistent pricing, promotions, and customer loyalty tracking",
        "Manufacturing firms in Dammam connecting sales orders directly to production scheduling",
        "Contracting businesses managing milestone-based billing and project sales",
        "E-commerce businesses in KSA integrating online orders with their ERP sales workflow"
      ]
    },
    complianceNote: "AdoxERP Sales Management is fully integrated with ZATCA's Fatoorah e-invoicing portal — covering both Phase 1 (Generation) and Phase 2 (Integration). Every sales invoice is automatically generated in compliant XML format, digitally signed, and submitted without manual steps. VAT is calculated and applied automatically according to Saudi Arabia's current VAT rate.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about Sales Management integration and compliance in Saudi Arabia.",
    faqs: [
      {
        question: "Can AdoxERP generate ZATCA-compliant invoices directly from a sales order in Saudi Arabia?",
        answer: "Yes. When a sales order is confirmed in AdoxERP, the system automatically generates a ZATCA-compliant e-invoice — formatted in the required XML structure, digitally signed, QR-coded, and submitted to the Fatoorah portal in real time. No manual steps, no third-party tools, no compliance risk."
      },
      {
        question: "Does AdoxERP Sales Management support Arabic quotations and invoices?",
        answer: "Fully. All sales documents — quotations, order confirmations, delivery notes, and invoices — can be generated in Arabic, English, or bilingual format. The system supports right-to-left Arabic layout natively across all printed and digital documents."
      },
      {
        question: "Can my sales team in Riyadh see live inventory availability when creating a quotation?",
        answer: "Yes. AdoxERP Sales Management is fully integrated with the Inventory module, which means your sales team sees real-time stock levels across all warehouses and locations when building a quotation or sales order. No more over-promising or back-orders due to outdated stock information."
      },
      {
        question: "How does AdoxERP handle customer pricing for different clients in Saudi Arabia?",
        answer: "AdoxERP supports tiered pricing, customer-specific price lists, quantity-based discounts, and promotional pricing — all enforced automatically by the system. You define the rules; AdoxERP applies them consistently across every transaction, every branch, and every salesperson."
      },
      {
        question: "Is AdoxERP Sales Management suitable for SMEs as well as large enterprises in KSA?",
        answer: "Yes. The Sales Management module is designed to scale from a small trading company in Jeddah with a handful of customers to a large distributor in Riyadh managing thousands of orders per month. You pay for what you need and add capacity as your business grows."
      }
    ]
  },
  "inventory-management": {
    slug: "inventory-management",
    title: "Inventory Management",
    metaTitle: "Inventory Management Software Saudi Arabia | AdoxERP Cloud ERP",
    metaDescription: "AdoxERP Inventory Management: real-time stock tracking across multiple warehouses in Riyadh, Jeddah & Dammam. Automated reorder alerts, barcode support & full ERP integration.",
    keywords: [
      "inventory management Saudi Arabia",
      "stock management software KSA",
      "warehouse management Riyadh",
      "inventory software Jeddah",
      "ERP inventory Dammam",
      "cloud inventory KSA",
      "multi-warehouse ERP"
    ],
    heroTitle: "Inventory Management Software for Saudi Arabia",
    heroSubtitle: "Always Know What You Have, Where It Is, and When to Reorder — Across Every Warehouse in the Kingdom",
    heroImage: "/img/features/inventory-mock.png",
    mainDescription: "Running out of stock costs you sales. Overstocking ties up cash. And managing inventory across multiple warehouses in Riyadh, Jeddah, Dammam, or anywhere across Saudi Arabia without a real-time system means you are always reacting rather than planning. AdoxERP Inventory Management gives you complete, live visibility of your stock — across every location, at every moment — so your business never has to choose between a stockout and a cash flow problem.",
    highlightStats: [
      { value: "Real-time", label: "Stock visibility" },
      { value: "Multi-site", label: "Warehouse tracking" },
      { value: "Auto", label: "Reorder alerts" },
      { value: "Barcode", label: "& RFID ready" }
    ],
    featuresTitle: "What Inventory Management Does in AdoxERP",
    featuresDescription: "AdoxERP Inventory Management tracks every product, in some warehouses, through every movement — from goods receipt to customer delivery. Stock levels update in real time as purchases are received, sales are dispatched, and inter-branch transfers are processed. The system connects directly to the Sales, Purchasing, and Manufacturing modules, so your sales team sees live availability, your buyers know exactly when to reorder, and your production team always knows what raw materials are on hand.",
    features: [
      {
        title: "Real-Time Stock Tracking",
        description: "See live stock levels for every product, in every warehouse and location, at any moment. Stock updates automatically when goods are received, orders are dispatched, returns are processed, or adjustments are made — no manual counts required between transactions."
      },
      {
        title: "Multi-Warehouse & Location Management",
        description: "Manage inventory across multiple warehouses, storage zones, and locations — from a single site in Jeddah to a network of distribution points across Saudi Arabia and the GCC. Transfer stock between locations with full traceability and no paperwork."
      },
      {
        title: "Automated Reorder Alerts & Purchase Orders",
        description: "Set minimum stock thresholds for each product and let AdoxERP do the rest. When stock drops below your defined level, the system automatically generates a reorder alert and — if configured — raises a draft purchase order for your approval."
      },
      {
        title: "Batch, Serial Number & Expiry Tracking",
        description: "Track products by batch, serial number, or expiry date through their entire lifecycle. Essential for food and beverage businesses, pharmaceutical distributors, medical device companies, and any industry where traceability and regulatory compliance are non-negotiable."
      },
      {
        title: "Barcode Scanning & RFID Integration",
        description: "Speed up goods receipt, stock takes, and order picking with full barcode scanning and RFID integration. AdoxERP works with standard barcode scanners and mobile devices, reducing manual entry errors and cutting warehouse processing times significantly."
      },
      {
        title: "Inventory Valuation & Cost Management",
        description: "AdoxERP supports FIFO, LIFO, and average cost inventory valuation methods. Know the exact value of your stock at any moment, track landed costs, and feed accurate inventory valuations directly into your accounting module automatically."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP Inventory Management in Saudi Arabia?",
      description: "AdoxERP Inventory Management is used by businesses across Saudi Arabia that depend on accurate, real-time stock control. It is particularly suited to trading and distribution companies in Riyadh managing large SKU counts, manufacturing businesses in Dammam needing raw material and WIP tracking, retail chains in Jeddah with multi-branch inventory, e-commerce businesses in KSA needing seamless ERP-to-storefront stock sync, and logistics companies managing goods on behalf of multiple clients.",
      userTypes: [
        "Trading and wholesale distributors in Riyadh with high-volume, multi-SKU operations",
        "Retail chains in Jeddah managing inventory across multiple store locations",
        "Manufacturing businesses in Dammam tracking raw materials, WIP, and finished goods",
        "E-commerce businesses in KSA needing live stock sync with their online store",
        "Food and beverage businesses requiring batch tracking and expiry date management"
      ]
    },
    complianceNote: "AdoxERP Inventory Management includes full audit trail logging for all stock movements, supporting internal controls and external audits. For businesses in regulated industries, batch and serial tracking provides the traceability documentation required by Saudi regulatory authorities.",
    faqTitle: "Frequently Asked Questions — Inventory Management in Saudi Arabia",
    faqDescription: "Everything you need to know about Inventory Management in Saudi Arabia.",
    faqs: [
      {
        question: "Can AdoxERP track inventory across multiple warehouses in different cities in Saudi Arabia?",
        answer: "Yes. AdoxERP Inventory Management is designed for multi-site operations. You can manage stock across any number of warehouses — whether that is two locations in Riyadh and Jeddah, or a nationwide distribution network across the Kingdom — with full real-time visibility from a single system."
      },
      {
        question: "How does AdoxERP handle automatic reordering when stock runs low?",
        answer: "AdoxERP allows you to set a minimum stock level (reorder point) for each product. When stock drops to or below that level, the system automatically generates a reorder alert and can raise a draft purchase order for your review and approval. This eliminates stockouts and removes the need for manual stock monitoring."
      },
      {
        question: "Does AdoxERP support barcode scanning for warehouse operations in Saudi Arabia?",
        answer: "Yes. AdoxERP supports barcode scanning and RFID integration throughout the inventory workflow — goods receipt, picking, packing, stock transfers, and physical stock counts. The system works with standard USB and Bluetooth barcode scanners, as well as mobile devices running the AdoxERP mobile app."
      },
      {
        question: "Can AdoxERP track inventory by batch number and expiry date for regulated industries?",
        answer: "Yes. AdoxERP supports batch tracking, serial number tracking, and expiry date management throughout the inventory lifecycle. This is particularly important for businesses in food & beverage, pharmaceuticals, and medical devices operating in Saudi Arabia where traceability is a regulatory requirement."
      },
      {
        question: "How does AdoxERP Inventory Management connect to the Sales and Purchasing modules?",
        answer: "AdoxERP's modules are fully integrated in real time. When a sales order is confirmed, inventory is automatically reserved. When a purchase order is received, stock levels update immediately. When stock falls below reorder points, a purchase request is raised automatically. Your sales, purchasing, and inventory teams always work from the same live data."
      }
    ]
  },
  "accounting-finance": {
    slug: "accounting-finance",
    title: "Accounting & Finance",
    metaTitle: "Accounting Software Saudi Arabia | VAT & ZATCA Compliant | AdoxERP",
    metaDescription: "AdoxERP Accounting & Finance: real-time bookkeeping, automated VAT, ZATCA e-invoicing & SAMA-compliant financial reporting for businesses in Riyadh, Jeddah & Dammam.",
    keywords: [
      "accounting software Saudi Arabia",
      "VAT accounting KSA",
      "ZATCA accounting software",
      "financial ERP Riyadh",
      "bookkeeping software Jeddah",
      "SAMA compliant accounting",
      "cloud accounting KSA"
    ],
    heroTitle: "Accounting & Finance Software Built for Saudi Arabia",
    heroSubtitle: "Real-Time Books. Automated VAT. Full ZATCA & SAMA Compliance — All in One Platform.",
    heroImage: "/img/accounting-finance-hero.png",
    mainDescription: "Managing your finances in Saudi Arabia means navigating VAT regulations, ZATCA e-invoicing mandates, SAMA financial guidelines, multi-currency transactions, and the daily demands of keeping accurate books — simultaneously. AdoxERP Accounting & Finance is built to handle all of it in one place, without the manual work, the month-end scramble, or the compliance anxiety. Your books are always up to date, your VAT is always accurate, and your financial reports are always audit-ready.",
    highlightStats: [
      { label: "VAT", value: "Auto-calculated" },
      { label: "ZATCA", value: "Phase 1 & 2 certified" },
      { label: "Real-time", value: "Financial reporting" },
      { label: "SAMA", value: "Compliant" }
    ],
    featuresTitle: "What Accounting Management Does in AdoxERP",
    featuresDescription: "AdoxERP Accounting & Finance gives finance teams across Saudi Arabia a complete, cloud-based general ledger with real-time transaction posting, automated VAT calculation, multi-currency support, bank reconciliation, accounts payable and receivable management, and financial reporting — all fully integrated with every other AdoxERP module. When a sale is made, the accounting entries are posted automatically. When a purchase order is raised, the liability is recorded. When payroll runs, the journal entries follow. Your books are always current, always complete.",
    features: [
      {
        title: "General Ledger & Chart of Accounts",
        description: "A fully configurable chart of accounts aligned with Saudi Arabia's GAAP and IFRS requirements. Every transaction across the business posts automatically to the correct account — no manual journal entries, no end-of-month catch-up work."
      },
      {
        title: "Automated VAT Calculation & Reporting",
        description: "AdoxERP calculates VAT on every applicable transaction automatically, generates VAT return summaries at the click of a button, and keeps a full transaction-level audit trail that satisfies ZATCA's reporting requirements."
      },
      {
        title: "ZATCA E-Invoicing Integration",
        description: "Every invoice issued through AdoxERP is automatically submitted to ZATCA's Fatoorah portal in real time — Phase 1 and Phase 2 certified. Rejections are flagged instantly with clear correction guidance. Full compliance, zero manual steps."
      },
      {
        title: "Multi-Currency & Exchange Rate Management",
        description: "Handle transactions in Saudi Riyals, USD, EUR, AED, and any other currency your business operates in. Exchange rates update automatically, currency gains and losses are calculated in real time, and your SAR reporting is always accurate."
      },
      {
        title: "Accounts Payable & Receivable",
        description: "Stay on top of what you owe and what you are owed. AdoxERP tracks invoice due dates, sends automated payment reminders, handles partial payments and credit notes, and gives your finance team a clear aging report at any moment."
      },
      {
        title: "Bank Reconciliation",
        description: "Connect your Saudi bank accounts directly to AdoxERP for automated transaction matching and bank reconciliation. Identify unmatched items instantly and close your books faster — with confidence."
      },
      {
        title: "Financial Reporting & AI Insights",
        description: "Generate profit & loss statements, balance sheets, cash flow reports, and custom management accounts in seconds — in Arabic or English. AdoxERP's AI reporting engine can also produce plain-language financial summaries for non-finance stakeholders."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP Accounting Management in Saudi Arabia?",
      description: "AdoxERP Accounting & Finance is used by finance teams across all business sizes and sectors in Saudi Arabia — from single-person accounting departments at growing SMEs in Dammam to multi-entity group finance functions in Riyadh. It is particularly valuable for businesses that need ZATCA compliance built into their daily accounting workflow, and for CFOs who need reliable, real-time financial visibility.",
      userTypes: [
        "CFOs and finance directors at mid-size and enterprise businesses in Riyadh needing consolidated group reporting",
        "Accounting teams at trading and distribution companies in Jeddah managing high transaction volumes",
        "Manufacturing businesses in Dammam needing cost accounting and production cost tracking",
        "Professional services firms billing clients in multiple currencies across the GCC",
        "SMEs across Saudi Arabia seeking an affordable, ZATCA-compliant alternative to legacy desktop accounting software"
      ]
    },
    complianceNote: "AdoxERP Accounting & Finance is fully certified for ZATCA e-invoicing (Phase 1 and Phase 2), supports automated VAT calculation and filing in line with ZATCA requirements, and is built to meet SAMA's financial regulations for businesses in the Kingdom. All financial data is stored with a full audit trail, and every record is exportable for tax authority review.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about Accounting Management, VAT, and ZATCA compliance in Saudi Arabia.",
    faqs: [
      {
        question: "Is AdoxERP accounting software fully compliant with ZATCA e-invoicing in Saudi Arabia?",
        answer: "Yes. AdoxERP is certified for both Phase 1 (Generation) and Phase 2 (Integration) of ZATCA's Fatoorah e-invoicing programme. Every invoice is automatically generated in compliant XML format, digitally signed, and submitted to the ZATCA portal in real time — with no manual steps required."
      },
      {
        question: "How does AdoxERP handle VAT calculations for businesses in Saudi Arabia?",
        answer: "AdoxERP calculates VAT automatically on every applicable transaction based on Saudi Arabia's current VAT rules. VAT amounts are broken out on invoices, tracked in your books, and summarised in a VAT return report that is ready to file. No manual calculations, no spreadsheets, no end-of-quarter scramble."
      },
      {
        question: "Can AdoxERP produce financial reports in Arabic for businesses in Riyadh and Jeddah?",
        answer: "Yes. All financial reports — including profit & loss statements, balance sheets, cash flow statements, and management accounts — can be generated in Arabic, English, or both. Arabic financial reporting with right-to-left formatting is fully supported throughout the platform."
      },
      {
        question: "Does AdoxERP support multi-currency accounting for Saudi businesses trading internationally?",
        answer: "Yes. AdoxERP handles transactions in SAR and all major international currencies. Exchange rates update automatically, currency gains and losses are calculated in real time, and your Saudi Riyal reporting always reflects the correct valuations."
      },
      {
        question: "What is the difference between ZATCA Phase 1 and Phase 2 compliance and does AdoxERP cover both?",
        answer: "ZATCA Phase 1 (Generation) requires businesses to generate e-invoices in a structured electronic format. Phase 2 (Integration) requires real-time submission and validation of invoices through the ZATCA Fatoorah API. AdoxERP is certified for both phases — invoices are generated in the correct XML format, digitally signed, and submitted to ZATCA in real time without any manual intervention."
      }
    ]
  },
  "manufacturing-production": {
    slug: "manufacturing-production",
    title: "Manufacturing & Production",
    metaTitle: "Manufacturing ERP Software Saudi Arabia | AdoxERP Production Management",
    metaDescription: "AdoxERP Manufacturing ERP for Saudi Arabia: production planning, BOM management, shop floor tracking & supply chain integration for factories in Dammam, Riyadh & Jeddah.",
    keywords: [
      "manufacturing ERP Saudi Arabia",
      "production management software KSA",
      "BOM software Dammam",
      "factory ERP Riyadh",
      "manufacturing software Eastern Province",
      "shop floor management Saudi Arabia"
    ],
    heroTitle: "Manufacturing ERP Software for Saudi Arabia",
    heroSubtitle: "Production Planning, Shop Floor Control & Supply Chain Integration — Built for Saudi Manufacturers",
    heroImage: "/img/manufacturing-hero.png",
    mainDescription: "Saudi Arabia's manufacturing sector is one of the most strategically important industries in the Kingdom — a pillar of Vision 2030's drive to diversify the economy. Whether you operate a factory in Dammam's industrial city, a production facility in Riyadh, or an assembly plant anywhere across the Kingdom, running an efficient manufacturing operation means having total visibility of your production floor, your supply chain, your workforce, and your costs — in real time. AdoxERP Manufacturing gives you exactly that.",
    highlightStats: [
      { label: "Shop floor visibility", value: "Real-time" },
      { label: "Multi-level support", value: "BOM" },
      { label: "Vision 2030 aligned", value: "Vision" },
      { label: "Supply chain integration", value: "Full" }
    ],
    featuresTitle: "What Manufacturing Management Does in AdoxERP",
    featuresDescription: "AdoxERP Manufacturing & Production brings together everything a Saudi manufacturer needs to plan, execute, and monitor production — from master production scheduling and bill of materials management to work order tracking, shop floor data capture, quality control, and finished goods inventory. The module connects directly to Inventory, Purchasing, Sales, HR, and Accounting — so your factory floor and your back office are always in sync.",
    features: [
      {
        title: "Production Planning & Scheduling",
        description: "Create master production schedules, plan production runs against sales forecasts and customer orders, and allocate machinery and labour resources to each job. AdoxERP's planning engine helps Saudi manufacturers balance demand against capacity in real time."
      },
      {
        title: "Bill of Materials (BOM) Management",
        description: "Build single-level and multi-level bills of materials for every product you manufacture. AdoxERP manages version control, engineering change orders, and BOM costing automatically — so your production team always works from the correct, up-to-date specification."
      },
      {
        title: "Work Order Management",
        description: "Issue, track, and close work orders with complete traceability from raw material consumption to finished goods output. Monitor work-in-progress (WIP) in real time, capture actual vs planned costs, and identify bottlenecks before they affect delivery dates."
      },
      {
        title: "Shop Floor Data Capture",
        description: "Capture real-time production data directly from the shop floor — machine run times, labour hours, output quantities, and quality checks — using mobile devices, barcode scanners, or fixed terminals. No paper, no delays, no data entry errors."
      },
      {
        title: "Quality Control & Inspection",
        description: "Define quality checkpoints at each stage of your production process. Record inspection results, manage non-conformances, and maintain a complete quality history for every batch or production run — supporting ISO certification and regulatory audit requirements."
      },
      {
        title: "Manufacturing Cost Accounting",
        description: "Track the full cost of every production run — raw materials, labour, machine time, and overhead. AdoxERP calculates actual manufacturing costs against standard costs in real time and feeds accurate cost of goods sold (COGS) data directly into your accounting module."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP Manufacturing Management in Saudi Arabia?",
      description: "AdoxERP Manufacturing is used by production businesses across Saudi Arabia's industrial sectors — from small assembly operations to large multi-shift factories. It is particularly suited to companies in Dammam's industrial cities, SABIC and petrochemical supply chain manufacturers, food and beverage producers, building materials manufacturers, and electronics assembly businesses supporting Vision 2030's domestic production targets.",
      userTypes: [
        "Factory managers and production directors at manufacturing companies in Dammam and the Eastern Province",
        "Operations managers at food and beverage producers in Riyadh and Jeddah",
        "Supply chain managers at industrial businesses in Saudi Arabia's Special Economic Zones",
        "Engineering directors managing complex multi-level BOMs and ECO processes",
        "CFOs of manufacturing businesses needing accurate production cost accounting and variance analysis"
      ]
    },
    complianceNote: "AdoxERP Manufacturing supports full traceability from raw material receipt to finished goods shipment, providing the documentation required for Saudi regulatory compliance, ISO certification audits, and SFDA requirements for applicable industries. All production costs feed directly into ZATCA-compliant invoicing and VAT reporting.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about Manufacturing ERP integration and compliance in Saudi Arabia.",
    faqs: [
      {
        question: "Can AdoxERP handle complex multi-level bills of materials for manufacturing companies in Saudi Arabia?",
        answer: "Yes. AdoxERP supports single-level and multi-level (nested) bills of materials with full version control, engineering change order management, and BOM costing. Changes to a BOM are reflected across all open work orders automatically, ensuring your production team always works from the current specification."
      },
      {
        question: "How does AdoxERP Manufacturing integrate with inventory and purchasing for a factory in Dammam?",
        answer: "Fully and automatically. When a production order is raised in AdoxERP, raw material requirements are checked against current inventory levels in real time. If materials are short, a purchase request is generated automatically. When materials arrive, stock levels update immediately and are available for production. Your supply chain, inventory, and production are always in sync."
      },
      {
        question: "Does AdoxERP support shop floor data capture for manufacturing operations in Saudi Arabia?",
        answer: "Yes. AdoxERP supports real-time shop floor data capture via mobile devices, barcode scanners, and fixed terminals. Operators can report job start and stop times, material consumption, output quantities, and quality check results directly from the production floor — eliminating paper-based processes and manual data entry delays."
      },
      {
        question: "Can AdoxERP track manufacturing costs and calculate cost of goods sold for Saudi manufacturers?",
        answer: "Yes. AdoxERP tracks the full cost of every production run in real time — raw materials consumed, labour hours, machine time, and overhead allocation. Actual costs are compared against standard costs automatically, giving your finance team accurate COGS data, production variance analysis, and profitability reporting that feeds directly into your accounting module."
      },
      {
        question: "Is AdoxERP Manufacturing suitable for businesses in Saudi Arabia's Vision 2030 industrial programme?",
        answer: "Yes. AdoxERP is aligned with Saudi Arabia's Vision 2030 industrial strategy — supporting local manufacturing, Saudization workforce targets, and the digital transformation agenda of the National Industrial Development and Logistics Programme (NIDLP). The system supports the operational, compliance, and reporting requirements of manufacturers operating within Saudi Arabia's industrial cities and special economic zones."
      }
    ]
  },
  "human-resources-payroll": {
    slug: "human-resources-payroll",
    title: "Human Resources & Payroll",
    metaTitle: "HR & Payroll Software Saudi Arabia | GOSI, Saudization & Labour Law | AdoxERP",
    metaDescription: "AdoxERP HR & Payroll: GOSI calculations, Saudization tracking, end-of-service, automated payroll & labour law compliance for businesses in Riyadh, Jeddah & Dammam, KSA.",
    keywords: [
      "HR software Saudi Arabia",
      "payroll software KSA",
      "GOSI calculation software",
      "Saudization tracking ERP",
      "HR ERP Riyadh",
      "payroll Jeddah",
      "end of service gratuity Saudi Arabia",
      "Nitaqat compliance software"
    ],
    heroTitle: "HR & Payroll Software Built for Saudi Arabia",
    heroSubtitle: "GOSI. Saudization. End-of-Service. Saudi Labour Law. All Automated — All in One Place.",
    heroImage: "/img/hr-payroll-hero.png",
    mainDescription: "Managing a workforce in Saudi Arabia is more complex than almost anywhere else in the world. Between GOSI contributions for Saudi and expat employees, Nitaqat (Saudization) targets, end-of-service benefit calculations, Iqama and visa tracking, and multi-nationality payroll — the administrative burden on HR teams is enormous. AdoxERP HR & Payroll eliminates that burden. Every Saudi-specific HR process — from hiring to offboarding — is automated, compliant with current Ministry of Human Resources guidelines, and fully integrated with your accounting and operations modules.",
    highlightStats: [
      { label: "GOSI", value: "Auto-calculated" },
      { label: "Saudization", value: "Nitaqat tracking" },
      { label: "EOS", value: "Benefit automation" },
      { label: "Multi-Nationality", value: "Payroll" }
    ],
    featuresTitle: "What HR Management Does in AdoxERP",
    featuresDescription: "AdoxERP HR & Payroll manages the complete employee lifecycle for Saudi and expatriate workers — recruitment, onboarding, contract management, attendance, leave, payroll processing, GOSI submissions, end-of-service calculations, and offboarding. Every process is built around Saudi Arabia's current labour law, with automatic updates when regulations change. The module connects directly to Accounting for payroll journal entries, and to Project Management for timesheet-based payroll.",
    features: [
      {
        title: "GOSI Calculation & Submission",
        description: "AdoxERP automatically calculates GOSI contributions for both Saudi national and expatriate employees at the correct rates, generates monthly GOSI submission reports in the required format, and maintains a full contribution history for every employee — eliminating manual calculation errors."
      },
      {
        title: "Saudization (Nitaqat) Tracking",
        description: "Track your current Saudization percentage in real time against Vision 2030 Nitaqat targets for your industry and company size. AdoxERP alerts you when your ratio approaches a compliance threshold, giving you time to plan hiring decisions proactively rather than reactively."
      },
      {
        title: "Automated Payroll Processing",
        description: "Run payroll for your entire workforce — Saudi nationals and expats, monthly and weekly paid — in minutes. AdoxERP calculates basic salary, allowances, deductions, GOSI contributions, and advances automatically, generates individual pay slips in Arabic and English, and posts payroll journal entries to Accounting without manual intervention."
      },
      {
        title: "End-of-Service Benefit Calculation",
        description: "AdoxERP calculates end-of-service gratuity automatically for every employee based on their tenure, salary, and reason for separation — in full compliance with Saudi Labour Law Article 84. Calculations update in real time as salaries change, ensuring you always have an accurate EOS liability figure."
      },
      {
        title: "Iqama, Visa & Document Expiry Tracking",
        description: "Track Iqama residency permits, work visas, medical certificates, and other employee documents by expiry date. AdoxERP sends automatic alerts before documents expire — protecting your business from penalties under the Ministry of Interior regulations for employing workers with expired documentation."
      },
      {
        title: "Leave & Attendance Management",
        description: "Manage annual leave, sick leave, Hajj leave, and other Saudi-specific leave entitlements in full compliance with Saudi Labour Law. Integrate with biometric attendance systems or the AdoxERP mobile app for real-time attendance tracking across all offices and sites."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP HR Management in Saudi Arabia?",
      description: "AdoxERP HR & Payroll is used by HR managers, payroll administrators, and business owners across Saudi Arabia who need to manage a Saudi and expat workforce in full compliance with local law. It is particularly valuable for businesses with large workforces in Riyadh, manufacturing and industrial companies in Dammam managing shift-based and contract workers, and any business with Vision 2030 Saudization obligations.",
      userTypes: [
        "HR managers at mid-size and large businesses in Riyadh managing mixed Saudi and expat workforces",
        "Payroll administrators at manufacturing companies in Dammam processing complex multi-shift payrolls",
        "Business owners at SMEs in Jeddah who need automated GOSI and Saudization compliance without a large HR team",
        "Group HR directors managing HR across multiple entities and cities in Saudi Arabia",
        "Contracting companies managing project-based workers with variable pay and allowance structures"
      ]
    },
    complianceNote: "AdoxERP HR & Payroll is built around Saudi Arabia's Labour Law, Ministry of Human Resources regulations, GOSI contribution requirements, and Vision 2030 Saudization (Nitaqat) targets. The system updates automatically when regulatory changes are announced, ensuring your HR processes remain compliant without manual rule updates.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about HR compliance, GOSI, and payroll in Saudi Arabia.",
    faqs: [
      {
        question: "How does AdoxERP calculate GOSI contributions for businesses in Saudi Arabia?",
        answer: "AdoxERP automatically calculates GOSI contributions for Saudi national employees (both employee and employer shares) and for expatriate workers (employer-only contribution for occupational hazard insurance) at the current statutory rates. Contribution amounts are calculated per payroll run, posted to accounting automatically, and summarised in a monthly GOSI submission report formatted for the GOSI portal."
      },
      {
        question: "Can AdoxERP track Saudization (Nitaqat) compliance for Vision 2030 in Saudi Arabia?",
        answer: "Yes. AdoxERP tracks your current Saudization percentage in real time, compares it against the Nitaqat targets for your industry classification and company size, and alerts you when your ratio approaches a threshold. This gives HR teams and business owners in Riyadh, Jeddah, and Dammam the visibility they need to plan hiring decisions proactively and maintain their Nitaqat green or platinum status."
      },
      {
        question: "How does AdoxERP calculate end-of-service benefits for employees in Saudi Arabia?",
        answer: "AdoxERP calculates end-of-service gratuity automatically for every employee when they leave, based on their length of service, final salary, and reason for termination — in full compliance with Saudi Labour Law Article 84. The calculation reflects the correct one-third, two-thirds, and full month entitlement rules for different tenure bands. You always know your EOS liability position in real time."
      },
      {
        question: "Does AdoxERP payroll software support Arabic payslips and reports for Saudi businesses?",
        answer: "Yes. All payroll documents — payslips, payroll summaries, GOSI reports, and HR letters — can be generated in Arabic, English, or bilingual format. Arabic payslips with right-to-left formatting are fully supported and can be distributed digitally via email or the AdoxERP employee self-service portal."
      },
      {
        question: "Can AdoxERP track Iqama and visa expiry dates for expat employees in Saudi Arabia?",
        answer: "Yes. AdoxERP maintains a complete document register for every expat employee — including Iqama residency permits, work visas, medical fitness certificates, and professional licences. The system sends automatic alerts to HR administrators a configurable number of days before any document expires, protecting businesses from Ministry of Interior penalties for employing workers with lapsed documentation."
      }
    ]
  },
  "crm-customer-management": {
    slug: "crm-customer-management",
    title: "CRM & Customer Management",
    metaTitle: "CRM Software Saudi Arabia | Customer Management ERP | AdoxERP",
    metaDescription: "AdoxERP CRM: manage customer relationships, sales pipelines & follow-ups for businesses in Riyadh, Jeddah & Dammam. Fully integrated with your ERP — no separate CRM tool needed.",
    keywords: [
      "CRM software Saudi Arabia",
      "customer management Riyadh",
      "sales pipeline software KSA",
      "CRM ERP Jeddah",
      "customer relationship management Dammam",
      "cloud CRM KSA",
      "Arabic CRM software"
    ],
    heroTitle: "CRM & Customer Management Software for Saudi Arabia",
    heroSubtitle: "Build Stronger Client Relationships — With a CRM That Lives Inside Your ERP",
    heroImage: "/img/crm-hero.png",
    mainDescription: "Most businesses in Saudi Arabia run their CRM in one system and their ERP in another — which means your sales team never has the full customer picture when they need it most. AdoxERP's CRM module is built directly into the ERP, which means your salespeople in Riyadh can see a customer's open invoices, order history, outstanding balance, and last interaction — all from the same screen. No switching. No syncing. No blind spots.",
    highlightStats: [
      { label: "Customer view", value: "360°" },
      { label: "Pipeline management", value: "Built-in" },
      { label: "Follow-up automation", value: "AI" },
      { label: "& English support", value: "Arabic" }
    ],
    featuresTitle: "What CRM Management Does in AdoxERP",
    featuresDescription: "AdoxERP CRM gives your sales and customer service teams a complete, integrated view of every customer — their contact details, interaction history, open opportunities, active orders, outstanding invoices, service requests, and account health — all in one place. The module connects directly to Sales, Accounting, and Service modules, so your team always has the full picture, and management always knows the health of the customer portfolio.",
    features: [
      {
        title: "Customer 360° Profile",
        description: "Every customer in AdoxERP has a unified profile showing all interactions, transactions, communications, open orders, invoices, and account history. Your sales team in Riyadh and your service team in Jeddah work from the same complete customer record — always."
      },
      {
        title: "Sales Pipeline Management",
        description: "Build and manage sales pipelines with custom stages that match how your business actually sells. Track deal value, close probability, expected close date, and next action for every opportunity — giving sales managers a real-time view of revenue in the pipeline."
      },
      {
        title: "Automated Follow-Up & Activity Management",
        description: "Set follow-up tasks, schedule calls, and assign activities to sales team members automatically based on pipeline stage or customer action. AdoxERP's AI agents send reminders, log completed activities, and flag overdue follow-ups — so no lead or customer goes cold by accident."
      },
      {
        title: "Lead & Opportunity Management",
        description: "Capture leads from your website, marketing campaigns, phone calls, and trade events in one place. Score them, assign them to the right salesperson, track their progress through the pipeline, and convert them to customers — with a full history from first touch to first sale."
      },
      {
        title: "Customer Segmentation & Targeting",
        description: "Segment your customer base by location (Riyadh, Jeddah, Dammam, GCC), industry, revenue, purchase history, or any custom criteria. Create targeted follow-up campaigns, identify at-risk accounts, and find upsell opportunities — all from within your ERP."
      },
      {
        title: "Service Requests & Issue Tracking",
        description: "Log and manage customer service requests, complaints, and support tickets directly in AdoxERP CRM. Assign them to the right team member, set SLA timers, track resolution status, and measure customer satisfaction — keeping your after-sales service as strong as your pre-sales process."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP CRM Management in Saudi Arabia?",
      description: "AdoxERP CRM is used by sales teams, customer service managers, and account directors at businesses across Saudi Arabia who want better customer visibility without the cost and complexity of a standalone CRM platform. It is particularly valuable for B2B businesses in Riyadh with long, complex sales cycles, distribution companies in Jeddah managing large customer accounts, and service businesses in Dammam where after-sales relationship management is as important as the sale itself.",
      userTypes: [
        "Sales directors and account managers at B2B companies in Riyadh managing large, complex customer relationships",
        "Distribution businesses in Jeddah needing full order and payment history alongside CRM interactions",
        "Service companies in Dammam managing service contracts, renewals, and after-sales support",
        "SME owners across Saudi Arabia who want a simple, effective CRM without a separate subscription",
        "Marketing and sales operations teams building outreach campaigns targeting customers in specific Saudi cities"
      ]
    },
    complianceNote: "AdoxERP CRM handles all customer personal data in full compliance with Saudi Arabia's Personal Data Protection Law (PDPL). Customer records are stored securely with role-based access controls, full audit logging, and data retention policies that meet PDPL requirements.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about CRM integration and customer data privacy in Saudi Arabia.",
    faqs: [
      {
        question: "What makes AdoxERP CRM different from a standalone CRM like Salesforce for businesses in Saudi Arabia?",
        answer: "The biggest difference is integration. AdoxERP CRM is built inside the ERP, which means your sales team sees a customer's invoices, open orders, payment history, and account balance alongside their CRM interactions — in the same screen, in real time. With a standalone CRM, you are always working with incomplete information because financial and operational data lives somewhere else."
      },
      {
        question: "Can AdoxERP CRM track sales pipelines for businesses with offices in Riyadh, Jeddah, and Dammam?",
        answer: "Yes. AdoxERP CRM gives sales managers a unified view of all pipelines across all offices and cities — filtered by location, salesperson, or team. Regional sales directors can see the Riyadh pipeline, the Jeddah pipeline, and the Dammam pipeline in one dashboard, or drill down into any individual deal at any time."
      },
      {
        question: "Does AdoxERP CRM support Arabic language for sales teams in Saudi Arabia?",
        answer: "Yes. AdoxERP CRM is fully bilingual — every screen, every report, and every customer communication template is available in Arabic and English. Sales teams can work entirely in Arabic, and customer communications such as follow-up emails, proposals, and service updates can be sent in Arabic, English, or both."
      },
      {
        question: "Can my sales team in Riyadh see if a customer has overdue invoices when discussing a new deal?",
        answer: "Yes. Because CRM and Accounting share the same database, your salesperson sees live financial status (outstanding balance, credit limit, payment history) directly on the customer's CRM profile. No more chasing finance for status updates before a sales call."
      },
      {
        question: "How does AdoxERP CRM handle customer data privacy under Saudi Arabia's PDPL?",
        answer: "AdoxERP stores all customer personal data in full compliance with Saudi Arabia's Personal Data Protection Law (PDPL). Data is stored within Saudi Arabia with encryption at rest and in transit, role-based access controls limit who can view sensitive customer information, and a full audit log records every access and change to customer records."
      }
    ]
  },
  "project-management": {
    slug: "project-management",
    title: "Project Management",
    metaTitle: "Project Management Software Saudi Arabia | ERP for Contracting & Vision 2030 | AdoxERP",
    metaDescription: "AdoxERP Project Management: plan, track & deliver projects on time in Saudi Arabia. Resource planning, cost tracking & billings — ideal for contracting firms & Vision 2030 projects.",
    keywords: [
      "project management software Saudi Arabia",
      "contracting ERP Riyadh",
      "project tracking KSA",
      "Vision 2030 project management",
      "construction ERP Saudi Arabia",
      "project billing software Jeddah",
      "ERP project management Dammam"
    ],
    heroTitle: "Project Management Software for Saudi Arabia",
    heroSubtitle: "Plan, Execute, and Deliver Projects On Time — Built for Saudi Contracting and Vision 2030",
    heroImage: "/img/project-management-hero.png",
    mainDescription: "Saudi Arabia is in the middle of one of the most ambitious project delivery programmes in the world. From NEOM to the Red Sea Project, from infrastructure upgrades in Riyadh to industrial developments in the Eastern Province, Vision 2030 is generating an unprecedented volume of project work across every sector. AdoxERP Project Management gives contracting companies, professional services firms, and project-driven businesses the tools to plan, resource, track, and bill their projects — all connected to their ERP accounting, HR, and procurement systems.",
    highlightStats: [
      { label: "Cost tracking", value: "Real-time" },
      { label: "Vision 2030", value: "Ready" },
      { label: "Milestone", value: "& phase billing" },
      { label: "Resource", value: "Planning" }
    ],
    featuresTitle: "What Project Management Does in AdoxERP",
    featuresDescription: "AdoxERP Project Management connects project planning, resource allocation, cost tracking, progress monitoring, and client billing into one integrated workflow. Project managers can build schedules with Gantt charts, assign resources from the HR module, track actual costs against budgets in real time, log timesheets, manage subcontractor commitments, and generate ZATCA-compliant invoices for milestone payments — all without leaving their ERP.",
    features: [
      {
        title: "Project Planning & Scheduling",
        description: "Build detailed project plans with tasks, milestones, dependencies, and timelines. Assign responsibilities to team members, set deadlines, and track progress against the baseline schedule — with Gantt chart visualisation and critical path identification."
      },
      {
        title: "Resource Planning & Allocation",
        description: "Assign people, equipment, and materials to project tasks from your existing HR and asset registers. See resource utilisation across all active projects in real time, identify over-allocation before it becomes a problem, and plan hiring or subcontracting needs proactively."
      },
      {
        title: "Budget & Cost Control",
        description: "Set project budgets at the task, phase, or overall level. Track committed costs, actual spend, and remaining budget in real time — with automatic alerts when costs approach budget thresholds. AdoxERP connects project costs directly to your accounting module for accurate P&L reporting."
      },
      {
        title: "Timesheet & Labour Cost Tracking",
        description: "Capture actual hours worked by employees and subcontractors against specific project tasks. Timesheets feed directly into payroll for labour cost calculation and into project accounts for accurate cost reporting — eliminating the disconnect between HR, Finance, and Project teams."
      },
      {
        title: "Milestone & Progress Billing",
        description: "Bill clients at project milestones, on a percentage completion basis, or against a defined payment schedule. AdoxERP generates ZATCA-compliant invoices for each billing event automatically, tracks payment status, and integrates cash received back into project financial reporting."
      },
      {
        title: "Subcontractor Management",
        description: "Manage subcontractor agreements, purchase orders, delivery milestones, and payment certificates within the project module. Track subcontractor costs against their contracts and ensure payment is tied to verified delivery — protecting your project margins."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP Project Management in Saudi Arabia?",
      description: "AdoxERP Project Management is used by contracting and project-driven businesses across Saudi Arabia — from civil engineering and MEP contractors working on Vision 2030 mega-projects to IT services firms, management consultancies, fit-out companies, and professional services businesses billing on a project or retainer basis.",
      userTypes: [
        "Contracting companies in Riyadh managing multiple concurrent projects with complex cost structures",
        "Engineering and construction firms in Jeddah working on large-scale public and private infrastructure projects",
        "MEP, fit-out, and specialist contracting businesses in Dammam and the Eastern Province",
        "IT and digital transformation firms delivering projects for Saudi government and enterprise clients",
        "Professional services firms billing on time-and-materials, fixed-fee, or milestone payment terms"
      ]
    },
    complianceNote: "AdoxERP Project Management is fully integrated with the ZATCA e-invoicing module, ensuring all milestone and progress billing invoices are automatically compliant with Saudi Arabia's Fatoorah requirements. Project costs are automatically posted to the accounting module for VAT reporting and audit purposes.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about Project Management for contracting and services in Saudi Arabia.",
    faqs: [
      {
        question: "Is AdoxERP Project Management suitable for contracting companies working on Vision 2030 projects in Saudi Arabia?",
        answer: "Yes. AdoxERP Project Management is specifically designed for the operational, financial, and compliance needs of contracting businesses in Saudi Arabia. It handles complex project cost structures, multi-party subcontractor management, milestone billing with ZATCA-compliant invoicing, and resource planning across large teams — all within a platform that also manages your accounting, HR, and payroll."
      },
      {
        question: "Can AdoxERP track actual project costs against budgets in real time for projects in Riyadh or Jeddah?",
        answer: "Yes. AdoxERP tracks committed costs (purchase orders, subcontractor agreements), actual costs (invoices received, timesheets approved), and remaining budget in real time for every project. Project managers and finance teams see the same live cost data, and automatic alerts are triggered when spending approaches budget thresholds."
      },
      {
        question: "How does AdoxERP handle milestone billing and ZATCA-compliant invoicing for project work?",
        answer: "When a project milestone is reached and approved, AdoxERP generates a ZATCA-compliant invoice automatically — formatted in the correct XML structure, QR-coded, and submitted to the Fatoorah portal in real time. Billing schedules can be defined per project, and the system tracks payment status against each milestone invoice automatically."
      },
      {
        question: "Can AdoxERP integrate project timesheets with payroll for businesses in Saudi Arabia?",
        answer: "Yes. Employee timesheets logged against project tasks in AdoxERP feed directly into the payroll module for labour cost calculation, and into the project accounts for cost reporting. This eliminates manual reconciliation between HR, Finance, and Project teams — and ensures your project cost reports reflect the true cost of labour."
      },
      {
        question: "Does AdoxERP Project Management support Arabic language for Saudi project teams?",
        answer: "Yes. All project management screens, reports, Gantt charts, and client-facing documents are available in Arabic and English. Project teams can work entirely in Arabic, and all project invoices, progress reports, and milestone certificates can be generated and sent in Arabic, English, or both."
      }
    ]
  },
  "asset-management": {
    slug: "asset-management",
    title: "Asset Management",
    metaTitle: "Asset Management Software Saudi Arabia | Fixed Assets ERP | AdoxERP",
    metaDescription: "AdoxERP Asset Management: track, depreciate & maintain every asset across your Saudi business. Full lifecycle management for businesses in Riyadh, Jeddah & Dammam — audit-ready.",
    keywords: [
      "asset management software Saudi Arabia",
      "fixed asset ERP KSA",
      "asset tracking Riyadh",
      "depreciation software Saudi Arabia",
      "fleet management ERP Jeddah",
      "asset register Dammam",
      "cloud asset management KSA"
    ],
    heroTitle: "Asset Management Software for Saudi Arabia",
    heroSubtitle: "Track Every Asset, Every Location, Every Stage of Its Lifecycle — Always Audit-Ready",
    heroImage: "/img/asset-management-hero.png",
    mainDescription: "Every asset your business owns — from vehicles and machinery to IT equipment and office furniture — represents a significant financial commitment. But most businesses in Saudi Arabia manage their assets in spreadsheets, lose track of where equipment is located, miss maintenance schedules, and claim incorrect depreciation amounts at year-end. AdoxERP Asset Management eliminates all of that. Every asset is tracked from purchase to disposal, depreciation is calculated automatically, maintenance is scheduled proactively, and your asset register is always audit-ready.",
    highlightStats: [
      { label: "Full", value: "Asset lifecycle tracking" },
      { label: "Auto", value: "Depreciation calc" },
      { label: "Scheduled", value: "Maintenance alerts" },
      { label: "Audit", value: "Ready at all times" }
    ],
    featuresTitle: "What Asset Management Does in AdoxERP",
    featuresDescription: "AdoxERP Asset Management maintains a complete register of every physical and intangible asset your business owns — with full lifecycle tracking from acquisition through depreciation, maintenance, revaluation, and eventual disposal. The module connects directly to Accounting for automatic depreciation journal entries, to Purchasing for new asset additions, and to HR for asset assignment to employees and locations.",
    features: [
      {
        title: "Asset Register & Classification",
        description: "Maintain a complete, structured register of all your business assets — classified by category, location, department, and cost centre. Every asset has a unique ID, a full history of ownership, location, maintenance, and financial treatment — accessible instantly for any audit or insurance review."
      },
      {
        title: "Automatic Depreciation Calculation",
        description: "AdoxERP calculates depreciation automatically for every asset using your chosen method — straight-line, declining balance, or units of production. Depreciation journals are posted to Accounting automatically at the close of each period. No spreadsheets, no manual calculations, no year-end catch-up."
      },
      {
        title: "Maintenance Scheduling & Tracking",
        description: "Set preventive maintenance schedules for every asset — annual vehicle services, quarterly equipment calibrations, monthly safety inspections. AdoxERP sends alerts before maintenance is due, logs completed maintenance with costs, and maintains a full service history that supports asset warranty claims and regulatory compliance."
      },
      {
        title: "Asset Location & Assignment Tracking",
        description: "Track where every asset is — which office, which site, which city, which employee it is assigned to. When assets move between locations — from your Riyadh office to a Dammam project site, for example — movements are recorded with date, reason, and responsible person."
      },
      {
        title: "Asset Disposal & Write-Off Management",
        description: "Record asset disposals, sales, and write-offs with full financial impact calculation — gain or loss on disposal, removal from the asset register, and automatic accounting journal entries. All disposal records are maintained for audit purposes."
      },
      {
        title: "Asset Revaluation & Insurance Management",
        description: "Revalue assets periodically to reflect fair market value, record impairment charges, and maintain insurance values for every asset. AdoxERP tracks insurance policy expiry dates and replacement value — so your business is always adequately covered and financially accurate."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP Asset Management in Saudi Arabia?",
      description: "AdoxERP Asset Management is used by operations managers, finance directors, and IT managers at businesses across Saudi Arabia that own significant physical assets — from vehicle fleets and construction equipment to IT infrastructure and production machinery. It is particularly valuable for construction and contracting companies with large equipment fleets in Dammam, manufacturing businesses in Riyadh with heavy machinery, and enterprises with IT assets spread across multiple office locations.",
      userTypes: [
        "Operations and fleet managers at construction and contracting companies in Dammam and the Eastern Province",
        "Finance directors at manufacturing companies in Riyadh needing accurate depreciation and CAPEX reporting",
        "IT managers at enterprises managing hardware and software assets across multiple Saudi offices",
        "CFOs at property and real estate businesses managing building, fit-out, and equipment assets",
        "Government contractors in Saudi Arabia needing audit-ready asset registers for contract compliance"
      ]
    },
    complianceNote: "AdoxERP Asset Management maintains a full, tamper-proof audit trail of every asset transaction — acquisition, depreciation, revaluation, maintenance, and disposal. This supports ZATCA-compliant financial reporting, internal audit requirements, and the fixed asset disclosure requirements under Saudi GAAP and IFRS as adopted in the Kingdom.",
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Everything you need to know about fixed asset management and depreciation in Saudi Arabia.",
    faqs: [
      {
        question: "How does AdoxERP calculate depreciation for fixed assets for businesses in Saudi Arabia?",
        answer: "AdoxERP calculates depreciation automatically for every asset using your preferred method — straight-line, declining balance (reducing balance), or units of production. The useful life, residual value, and depreciation method are set per asset or asset category. Depreciation is calculated at each period close and posted to the correct accounting cost centres automatically — with no manual journal entries required."
      },
      {
        question: "Can AdoxERP track assets across multiple office locations in Riyadh, Jeddah, and Dammam?",
        answer: "Yes. AdoxERP's asset register tracks the location of every asset — by office, site, warehouse, city, or individual employee assignment. When an asset moves — from your Jeddah head office to a Dammam project site, for example — the transfer is recorded with the date, reason, and authorising person, giving you a complete movement history for every item."
      },
      {
        question: "Does AdoxERP support preventive maintenance scheduling for equipment and vehicles in KSA?",
        answer: "Yes. You can define maintenance schedules for any asset type — annual vehicle services, quarterly equipment inspections, monthly safety checks. AdoxERP sends alerts to the responsible team member before each maintenance event is due, logs all completed maintenance with costs and service provider details, and maintains a searchable service history for every asset."
      },
      {
        question: "How does AdoxERP handle asset disposals and the accounting entries for businesses in Saudi Arabia?",
        answer: "When an asset is disposed of — sold, scrapped, written off, or transferred out — AdoxERP calculates the gain or loss on disposal automatically based on the net book value at the disposal date. The system removes the asset from the register, posts the correct accounting journal entries (removing cost, accumulated depreciation, and recording the disposal gain or loss), and creates a disposal record for audit purposes."
      },
      {
        question: "Is AdoxERP Asset Management suitable for businesses with large vehicle fleets in Saudi Arabia?",
        answer: "Yes. AdoxERP Asset Management handles fleets of vehicles as part of the broader asset register — tracking registration details, insurance expiry, service schedules, mileage, fuel consumption (if integrated), driver assignments, and maintenance costs per vehicle. Fleet managers in Dammam or Riyadh can see the full cost and maintenance status of every vehicle in real time."
      }
    ]
  },
  "ecommerce-management": {
    slug: "ecommerce-management",
    title: "E-Commerce Management",
    metaTitle: "E-Commerce ERP Integration Saudi Arabia | Shopify, Salla & Zid | AdoxERP",
    metaDescription: "AdoxERP E-Commerce Management: connect your Shopify, Salla or Zid store to your ERP in Saudi Arabia. Auto-sync orders, inventory & customers — powered by AI, ZATCA compliant.",
    keywords: [
      "e-commerce ERP Saudi Arabia",
      "Shopify ERP integration KSA",
      "Salla ERP integration",
      "Zid ERP Saudi Arabia",
      "online store ERP Riyadh",
      "e-commerce management Jeddah",
      "inventory sync e-commerce KSA"
    ],
    heroTitle: "E-Commerce Management Software for Saudi Arabia",
    heroSubtitle: "Connect Your Online Store to Your ERP — Orders, Inventory, Customers and Payments, Fully Synced",
    heroImage: "/img/ecommerce-management-hero.png",
    mainDescription: "Saudi Arabia's e-commerce market is one of the fastest growing in the world — projected to reach $13 billion by 2025. But growth creates operational complexity. Managing orders from Salla, Zid, Shopify, or your own website alongside your physical operations — without a connected ERP — means manual syncing, stock discrepancies, duplicate customer records, and accounting nightmares. AdoxERP E-Commerce Management eliminates all of that by connecting your online store directly to your ERP, in real time.",
    highlightStats: [
      { label: "Order & stock sync", value: "Real-time" },
      { label: "& Shopify ready", value: "Salla, Zid" },
      { label: "Compliant orders", value: "ZATCA" },
      { label: "Demand forecasting", value: "AI" }
    ],
    featuresTitle: "What E-Commerce Management Does in AdoxERP",
    featuresDescription: "AdoxERP E-Commerce Management creates a live, bidirectional connection between your online store and your ERP. When an order is placed on your website, it appears in AdoxERP instantly — with inventory reserved, the customer record updated, a ZATCA-compliant invoice generated, and the accounting entry posted. When stock is updated in AdoxERP following a purchase, it updates on your storefront automatically. Your online and offline operations become one unified business — not two separate systems that need constant reconciliation.",
    features: [
      {
        title: "Native Integration with Salla, Zid & Shopify",
        description: "AdoxERP connects natively with Saudi Arabia's leading e-commerce platforms — Salla, Zid, and Shopify — plus WooCommerce and custom API integrations. Orders, customers, products, and inventory sync in real time, bidirectionally, without manual exports or imports."
      },
      {
        title: "Real-Time Inventory Sync Across Channels",
        description: "Stock levels in AdoxERP update the moment an online order is placed — and your storefront stock counts update in real time when goods are received or returned in the warehouse. No more selling items that are out of stock. No more manual stock updates between your e-commerce dashboard and your ERP."
      },
      {
        title: "Automated ZATCA-Compliant E-Invoice Generation",
        description: "Every online order in AdoxERP automatically generates a ZATCA-compliant e-invoice — formatted in XML, QR-coded, and submitted to the Fatoorah portal in real time. Saudi e-commerce businesses meet their invoicing obligations automatically, for every transaction, without any manual steps."
      },
      {
        title: "Unified Customer Records",
        description: "Every customer who purchases online is automatically created or updated in your AdoxERP CRM. Their full purchase history — across your online store and any physical locations — is visible in one profile. This powers better customer service, targeted marketing, and accurate loyalty programme management."
      },
      {
        title: "Multi-Channel Order Management",
        description: "Manage orders from your website, Salla store, Zid platform, physical point of sale, and B2B sales team — all in one unified order management interface. Prioritise fulfilment, route orders to the correct warehouse, and track delivery status across all channels from a single view."
      },
      {
        title: "AI-Powered Demand Forecasting for E-Commerce",
        description: "AdoxERP's AI engine analyses your e-commerce sales history, seasonal trends, and promotional patterns to forecast future demand by product and category. This means your buying team always has the right stock before peak periods — whether that is Ramadan, National Day, or a flash sale event."
      }
    ],
    whoUsesSection: {
      title: "Who Uses AdoxERP E-Commerce Management in Saudi Arabia?",
      description: "AdoxERP E-Commerce Management is used by Saudi e-commerce businesses of every size — from single-brand direct-to-consumer stores on Salla or Zid to multi-category retailers managing large product catalogues and multi-warehouse fulfilment. It is particularly valuable for brands growing rapidly in Saudi Arabia's digital economy who have outgrown manual processes and need their ERP and e-commerce operations to work as one.",
      userTypes: [
        "DTC brands in Saudi Arabia selling on Salla or Zid who need ERP integration without enterprise-level complexity",
        "Retailers in Jeddah and Riyadh running both physical stores and e-commerce operations who need unified inventory",
        "Wholesale and B2B businesses in KSA adding a D2C e-commerce channel alongside their traditional sales operation",
        "E-commerce businesses scaling rapidly in Saudi Arabia who need automated ZATCA invoicing for every online order",
        "Multi-brand operators managing several online stores from a single ERP backend"
      ]
    },
    complianceNote: "AdoxERP E-Commerce Management generates a ZATCA-compliant e-invoice for every online order automatically — Phase 1 and Phase 2 certified. Saudi e-commerce businesses do not need a separate invoicing system; every sale, return, and credit note is handled in full compliance with ZATCA's Fatoorah requirements.",
    faqTitle: "Frequently Asked Questions — E-Commerce Management in Saudi Arabia",
    faqDescription: "Everything you need to know about e-commerce platform integration and ZATCA compliance.",
    faqs: [
      {
        question: "Can AdoxERP integrate with Salla and Zid e-commerce platforms in Saudi Arabia?",
        answer: "Yes. AdoxERP connects natively with Salla and Zid — Saudi Arabia's leading e-commerce platforms — as well as Shopify, WooCommerce, and custom storefronts via our open API. Orders, products, inventory, and customer data sync bidirectionally in real time between your storefront and your ERP."
      },
      {
        question: "How does AdoxERP handle ZATCA e-invoicing for online orders from Saudi customers?",
        answer: "Every order placed through your connected e-commerce store automatically generates a ZATCA-compliant e-invoice in AdoxERP — formatted in the required XML structure, digitally signed, QR-coded, and submitted to the Fatoorah portal in real time. Saudi e-commerce businesses meet their invoicing obligations for every transaction automatically, without any manual steps."
      },
      {
        question: "Can AdoxERP prevent overselling by syncing inventory in real time between my store and my warehouse in Saudi Arabia?",
        answer: "Yes. AdoxERP maintains a single, live inventory figure for every product across all channels. When an order is placed online, inventory is reserved immediately. When stock is received in the warehouse, it becomes available on the storefront automatically. This eliminates the overselling and stock discrepancy problems that come from managing e-commerce and warehouse inventory in separate systems."
      },
      {
        question: "Does AdoxERP support multi-channel e-commerce for businesses selling on multiple platforms in KSA?",
        answer: "Yes. AdoxERP can manage orders from multiple e-commerce channels — Salla, Zid, Shopify, WooCommerce, and B2B portals — in a single unified order management interface. Each channel can have its own pricing, promotions, and fulfilment rules, while inventory is managed centrally across all channels."
      },
      {
        question: "Can AdoxERP forecast demand for e-commerce businesses in Saudi Arabia before peak periods like Ramadan?",
        answer: "Yes. AdoxERP's AI demand forecasting engine analyses your historical e-commerce sales data, seasonal patterns, and promotional history to forecast demand by product and category — weeks or months in advance. This means your buying team can stock up before Ramadan, National Day sales, or any planned promotional period — with data-driven confidence rather than guesswork."
      }
    ]
  }
};
